### ISSUE TITLE
No Godot file?

### ISSUE THREAD

**Issue by ghost** [MarianoGnu/Pokemon-Tutorials#1]
There's no Godot file! Do we need to build it up using the assets?

**Comment by MarianoGnu** [comment]
Hi.
This tutorials where made with an old version of godot, so theres not a project file.
If you want to port this you will have to create a new project, drag textures and scripts and recreate the scenes (since some clases where renamed they wont work in Godot 3)

**Comment by ghost** [comment]
Ah, ok. Thanks
